# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pygenv',
                'doc_host': 'https://tkukurin.github.io',
                'git_url': 'https://github.com/tkukurin/pygenv',
                'lib_path': 'pygenv'},
  'syms': { 'pygenv.core': { 'pygenv.core.GlobalEnv': ('core.html#globalenv', 'pygenv/core.py'),
                             'pygenv.core.GlobalEnv.__init__': ('core.html#globalenv.__init__', 'pygenv/core.py'),
                             'pygenv.core.GlobalEnv.activate': ('core.html#globalenv.activate', 'pygenv/core.py'),
                             'pygenv.core.GlobalEnv.exists': ('core.html#globalenv.exists', 'pygenv/core.py'),
                             'pygenv.core.GlobalEnv.feats': ('core.html#globalenv.feats', 'pygenv/core.py'),
                             'pygenv.core.ProcResult': ('core.html#procresult', 'pygenv/core.py'),
                             'pygenv.core.cli': ('core.html#cli', 'pygenv/core.py'),
                             'pygenv.core.make_or_activate': ('core.html#make_or_activate', 'pygenv/core.py'),
                             'pygenv.core.sprun': ('core.html#sprun', 'pygenv/core.py')}}}
